### ISSUE TITLE
fix bug unable to parse property of map with nil value

### ISSUE THREAD

**Issue by novalagung** [eaciit/toolkit#50]
Using `toolkit.ToM` on any object that has property with a map type, and on the map object itself there is some item that the value is zero value, then the execution of `ToM` will generate panic error.

Test File:

```go
package main

import (
	"fmt"
	"strings"

	"github.com/eaciit/toolkit"
)

var jsString = `{
    "_id": "5c00edd577b8a9955600005d",
    "client": "ONGC",
    "mwd": {
      "mwd_details": null,
      "mwd_include_additional_items": [],
      "mwd_kit": null,
      "mwd_option": "NO"
    }
  }`

func main() {
	res := make(map[string]interface{})
	toolkit.UnjsonFromString(strings.TrimSpace(jsString), &res)

	res, err := toolkit.ToM(res)
	fmt.Println(res, err)
}
```

Error Stack Trace

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/reflect/value.go:1743 +0x16c
github.com/eaciit/toolkit.ToM(0x1284820, 0xc000083a10, 0x94, 0x1284820, 0xc000083a10)
	/Volumes/Nightwing/go/src/github.com/eaciit/toolkit/m.go:105 +0x751
github.com/eaciit/toolkit.ToM(0x1284820, 0xc000083890, 0x1268800, 0xc0000965b8, 0x0)
	/Volumes/Nightwing/go/src/github.com/eaciit/toolkit/m.go:109 +0x869
main.main()
	/Users/novalagung/desktop/test2.go:126 +0xc0
exit status 2
```

**Comment by novalagung** [comment]
https://github.com/eaciit/toolkit/pull/49
