### ISSUE TITLE
ToM function error on map[string]string and private attribute

### ISSUE THREAD

**Issue by raditzlawliet** [eaciit/toolkit#51]
new toolkit got panic when using ToM from struct having extend, private attribute or map[string]string with value.

Using Version SHA-1: 40bb79018cf134f4236212f2ff65f61f53224016
Expected: Working smoothly
Actual: 
```
=== RUN   Test_ToM1
--- FAIL: Test_ToM1 (0.00s)
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
	panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 19 [running]:
testing.tRunner.func1(0xc0421582d0)
	C:/Go/src/testing/testing.go:742 +0x2a4
panic(0x73b9a0, 0x811b80)
	C:/Go/src/runtime/panic.go:505 +0x237
reflect.valueInterface(0x76f720, 0xc042162000, 0xb4, 0x1, 0x1, 0x0)
	C:/Go/src/reflect/value.go:959 +0x1c8
reflect.Value.Interface(0x76f720, 0xc042162000, 0xb4, 0x0, 0x76f720)
	C:/Go/src/reflect/value.go:948 +0x4b
eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit.ToM(0x7644c0, 0xc042162000, 0x99, 0x7644c0, 0xc042162000)
	D:/Go Project/src/eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit/m.go:94 +0x414
eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit.ToM(0x7b7740, 0xc042162000, 0x7b7740, 0xc042162000, 0x986dfc)
	D:/Go Project/src/eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit/m.go:82 +0x2b2
eaciit/dmt/webapp/helper.Test_ToM1(0xc0421582d0)
	D:/Go Project/src/eaciit/dmt/webapp/helper/toolkit_test.go:48 +0x107
testing.tRunner(0xc0421582d0, 0x7e5f58)
	C:/Go/src/testing/testing.go:777 +0xd7
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:824 +0x2e7
FAIL	eaciit/dmt/webapp/helper	0.056s
Error: Tests failed.
```
```
=== RUN   Test_ToM2
--- FAIL: Test_ToM2 (0.00s)
panic: reflect: call of reflect.Value.Elem on string Value [recovered]
	panic: reflect: call of reflect.Value.Elem on string Value

goroutine 6 [running]:
testing.tRunner.func1(0xc04213c2d0)
	C:/Go/src/testing/testing.go:742 +0x2a4
panic(0x7526c0, 0xc0421034c0)
	C:/Go/src/runtime/panic.go:505 +0x237
reflect.Value.Elem(0x73b9a0, 0xc042128380, 0x98, 0x73b9a0, 0xc042128370, 0x98)
	C:/Go/src/reflect/value.go:775 +0x1be
eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit.ToM(0x756680, 0xc042126cf0, 0x95, 0x756680, 0xc042126cf0)
	D:/Go Project/src/eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit/m.go:105 +0x5d9
eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit.ToM(0x7b6420, 0xc04213c3c0, 0x7b6420, 0xc04213c3c0, 0xc042097708)
	D:/Go Project/src/eaciit/dmt/webapp/vendor/github.com/eaciit/toolkit/m.go:82 +0x2b2
eaciit/dmt/webapp/helper.Test_ToM2(0xc04213c2d0)
	D:/Go Project/src/eaciit/dmt/webapp/helper/toolkit_test.go:87 +0x160
testing.tRunner(0xc04213c2d0, 0x7e5f60)
	C:/Go/src/testing/testing.go:777 +0xd7
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:824 +0x2e7
FAIL	eaciit/dmt/webapp/helper	0.063s
Error: Tests failed.
```

Here my test case 
```
package helper

import (
	"testing"
	"time"

	"github.com/eaciit/orm"
	"github.com/eaciit/toolkit"
)

func Test_ToM1(t *testing.T) {
	example := struct {
		orm.ModelBase `bson:"-" json:"-"`
		Id            string `bson:"_id"`
		Value         string
		Name          string
		IsActive      bool
		Type          string
		Desc          string
		OptionalField map[string]string
		Status        int
		PendingStatus string
		Remark        string
		RemarkMaker   string
		ModeUpdate    string
		Checker       string
		CheckedBy     string
		UPDT_BY       string
		UPDT_DT       time.Time
	}{
		Id:            "1",
		Value:         "",
		Name:          "",
		IsActive:      false,
		Type:          "",
		Desc:          "",
		OptionalField: map[string]string{},
		Status:        0,
		PendingStatus: "",
		Remark:        "",
		RemarkMaker:   "",
		ModeUpdate:    "",
		Checker:       "",
		CheckedBy:     "",
		UPDT_BY:       "",
		UPDT_DT:       time.Now(),
	}
	m, _ := toolkit.ToM(example)
	t.Log(m)
}
func Test_ToM2(t *testing.T) {
	example := struct {
		Id            string `bson:"_id"`
		Value         string
		Name          string
		IsActive      bool
		Type          string
		Desc          string
		OptionalField map[string]string
		Status        int
		PendingStatus string
		Remark        string
		RemarkMaker   string
		ModeUpdate    string
		Checker       string
		CheckedBy     string
		UPDT_BY       string
		UPDT_DT       time.Time
	}{
		Id:            "",
		Value:         "",
		Name:          "",
		IsActive:      false,
		Type:          "",
		Desc:          "",
		OptionalField: map[string]string{"a": "b"},
		Status:        0,
		PendingStatus: "",
		Remark:        "",
		RemarkMaker:   "",
		ModeUpdate:    "",
		Checker:       "",
		CheckedBy:     "",
		UPDT_BY:       "",
		UPDT_DT:       time.Now(),
	}
	m, _ := toolkit.ToM(example)
	t.Log(m)
}

```

**Comment by ariefdarmawan** [comment]
Please pull latest from master
